version: '3'

services:

    php81-service:
        build:
            dockerfile: ./Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - /var/www/html/vendor
            - ./nette-blog:/var/www/html

    nginx-service:
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
           - ./nette-blog:/var/www/html
           - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
           - php81-service
